name: Python Style Check

on:
  push:
    branches:
      - main

concurrency:
  group: dep-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  python-style:
    name: Python Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff 
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # dotenv-linter

      - name: Ruff Check
        run: |
          ruff check .

      # - name: Dotenv Check
      #   run: |
      #     dotenv-linter ./api/.env.example ./web/.env.example

      - name: Lint Hints
        if: failure()
        run: echo "Please run 'dev/reformat' to fix the fixable linting errors."
